### ISSUE TITLE
通识课，摄影艺术创作

### ISSUE THREAD

**Issue by georgeghl** [INFO-studio/CQU-openlib#12]
[打印店资料.zip](https://github.com/user-attachments/files/16466842/default.zip)
[PPT整合-img.001.zip](https://github.com/user-attachments/files/16466851/PPT.-img.001.zip)
[PPT整合-img.003.zip](https://github.com/user-attachments/files/16466854/PPT.-img.003.zip)
[PPT整合-img.002.zip](https://github.com/user-attachments/files/16466855/PPT.-img.002.zip)

**Comment by INFO-studio** [comment]
已更新至[摄影艺术创作](https://cqu-openlib.cn/%E8%AF%BE%E7%A8%8B/%E9%80%9A%E8%AF%86%E8%AF%BE/%E6%91%84%E5%BD%B1%E8%89%BA%E6%9C%AF%E5%88%9B%E4%BD%9C/)
