### ISSUE TITLE
数学实验 ( MATH21011 ) 

### ISSUE THREAD

**Issue by MapleandKaede** [INFO-studio/CQU-openlib#13]
航空航天工程
老师分享的电子书
[数学实验教材电子版（刘琼荪主编）.pdf](https://github.com/user-attachments/files/16859065/default.pdf)

**Comment by MapleandKaede** [comment]
数学实验
刘琼荪2004-07
第1版高等教育出版社
978-7-04-014409-3境内教材

补充

**Comment by INFO-studio** [comment]
请提供本课程的课程代码捏

**Comment by MapleandKaede** [comment]
> 请提供本课程的课程代码捏
MATH21011
title里有捏，哈哈

**Comment by INFO-studio** [comment]
喔喔 感谢了

**Comment by INFO-studio** [comment]
已收录
https://cqu-openlib.cn/%E8%AF%BE%E7%A8%8B/%E6%95%B0%E5%AD%A6%E5%AE%9E%E9%AA%8C/#__tabbed_1_2
