### ISSUE TITLE
热力学与统计物理EST20000

### ISSUE THREAD

**Issue by bluebroken** [INFO-studio/CQU-openlib#16]
热力学与统计物理老师ppt
[第八章热统.pdf](https://github.com/user-attachments/files/18226596/default.pdf)
[第二章热统.pdf](https://github.com/user-attachments/files/18226597/default.pdf)
[第六章热统.pdf](https://github.com/user-attachments/files/18226598/default.pdf)
[第七章热统.pdf](https://github.com/user-attachments/files/18226599/default.pdf)
[第三章.pdf](https://github.com/user-attachments/files/18226600/default.pdf)
[第四章热统.pdf](https://github.com/user-attachments/files/18226601/default.pdf)
[第一章.pdf](https://github.com/user-attachments/files/18226602/default.pdf)

同时推荐我自己写的笔记[https://github.com/bluebroken/Thermodynamics-and-Statistical-Physics](url)

**Comment by INFO-studio** [comment]
感谢您的贡献🙏
以下是一些您需要知悉的事项，我们会尊重您的所有选择：

1. 您可以提供一个署名以陈列在文件对应位置处或[贡献者](https://cqu-openlib.cn/%E8%B4%A1%E7%8C%AE%E8%80%85/)一栏，当然也可以匿名。如您同意，您也可以额外提供一个个人介绍的md文件，我们也会放在[贡献者](https://cqu-openlib.cn/%E8%B4%A1%E7%8C%AE%E8%80%85/)一栏，同时在您提供的资料处超链接至此文件。
2. 关于笔记，由于众所周知原因，为了下载便利，我们提倡将文件至于本站云存储中，但您也可选择只链接原库github或自行提供额外下载链接。
3. 同时，笔记有您的真实姓名等信息，为确保您的信息安全，请确认知晓您的文件会被原封不动上传至本站。您也可以自行修改或由我们代为重新渲染并链接一个不包含个人信息的文件。

**Comment by INFO-studio** [comment]
感谢您的贡献🙏
目前您的贡献已被收录🎉
本次更新相关页面：
- [commit](https://github.com/INFO-studio/CQU-openlib/commit/e92e284fd0197890b6bb992ccf18a18cc43b5d2f)
- [更新日志](https://cqu-openlib.cn/sundry/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97/2024/2024-12/2024-12-26/)
- [热力学与统计物理学](https://cqu-openlib.cn/course/%E7%83%AD%E5%8A%9B%E5%AD%A6%E4%B8%8E%E7%BB%9F%E8%AE%A1%E7%89%A9%E7%90%86%E5%AD%A6/)
- [brokenblue](https://cqu-openlib.cn/contributor/brokenblue/)

课程笔记在您认为更新结束后也可重新考虑[上述](https://github.com/INFO-studio/CQU-openlib/issues/16#issuecomment-2561869199)2、3点，如有修改欢迎reopen此issue
